```python
import requests

def check_if_content_is_ai_generated(text):
    """
    Check if the provided text content was generated by an AI model.

    Parameters:
    text (str): The text content to be analyzed.

    Returns:
    dict: A dictionary containing the analysis results with keys 'is_ai_generated' and 'confidence'.
    """
    # Replace 'YOUR_API_ENDPOINT' with the actual endpoint of the AI detection service
    api_endpoint = 'YOUR_API_ENDPOINT'
    payload = {'text': text}
    headers = {'Content-Type': 'application/json'}

    try:
        response = requests.post(api_endpoint, json=payload, headers=headers)
        response.raise_for_status()
        result = response.json()
        return {
            'is_ai_generated': result.get('is_ai_generated', False),
            'confidence': result.get('confidence', 0)
        }
    except requests.RequestException as e:
        # Log the error details for debugging purposes
        print(f"An error occurred while checking if content is AI-generated: {e}")
        return {
            'is_ai_generated': None,
            'confidence': None
        }
```